### ISSUE TITLE
Small API improvement: Expiry

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#766]
Requesting storage has a field 'expiry', which is a Unix timestamp.
It must be in the future, and it must be no further in the future than now + 'duration'.
It would be a very convenient improvement if we could change this to be like duration: a number of seconds.
Duration is a number of seconds and implicitly converts to a timestamp, x seconds from the contract-started moment.
Expiry could be a number of seconds that implicitly converts to a timestamp x seconds from the moment the contract was posted.

**Comment by AuHau** [comment]
Yeah, I guess that is reasonable, also because we have currently the parameter `duration` specified in the same fashion so it would make sense to unite these to parameters.

**Comment by benbierens** [comment]
When I need to retry the request, I can just hit send again. Instead of having to calculate a new timestamp that's now + (duration - 1) every time :o

**Comment by AuHau** [comment]
A question - with this change the `expiry` won't have to be mandatory anymore (currently it is). Actually, it didn't have to be mandatory because I found in code [default value set by Mark](https://github.com/codex-storage/nim-codex/blob/61ec4275c82faf3545e435bfb6a0551e65a882da/codex/purchasing.nim#L25).

My question then is if we should enforce the configuration of the value or have a default value? Currently, it is set for 1 hour.
There would be quite a nasty edge-case there though. If somebody would create a storage request with a duration smaller than 1 hour (which is from what I saw very common in testnet "testing" cases) without specifying expiry, then we would have to error out as it is not allowed to have an expiry larger then request's duration. 

WDYT?

**Comment by benbierens** [comment]
> WDYT?

I think requiring an explicit `expiry` field is the nicest option. I love sane defaults, but because our use-cases have such a wide range, it's impossible to say what a sane default would be. Maybe 1h expiry makes sense when uploading large datasets? But when I'm uploading from a mobile device, probably I want confirmation that my contract is started (or timed out) much sooner?
